# Site settings

title: Jekyll Theme - Lazy
description: It is minimal and lazy!

email: koko@rhyndo.com
baseurl: "/jekyll-theme-lazy" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: kdankov
github_username: kdankov

future: true
markdown: kramdown
plugins:
  - jekyll-feed

destination: docs

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - docs
  - node_modules
  - scss
